initial project setup
eclipsesource/jsonforms-ui-schema-editor pull request #6
Opened 2018-04-10 14:35 UTC by AhmetTanakol

- Create a project scaffolding
- Configure Travis to run tests and lint check
- Setup Jest and tslint

Fixes #1 #2 #3 #4

2018-04-12 13:11 UTC, edgarmueller requested changes
Looks good, I'd propose to fix the comments made regarding the UI schema, everything else also can be fixed later, given we create the respective issues.

2018-04-12 13:11 UTC, edgarmueller commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/AhmetTanakol/jsonforms-ui-schema-editor/badge.svg?branch=master)](https://coveralls.io/github/AhmetTanakol/jsonforms-ui-schema-editor?branch=mast
This should point to upstream rather than your fork. ('ve enabled coveralls for upstream).

2018-04-12 13:11 UTC, edgarmueller commented on public/index.html
> +    <title>React App</title>
Change title

2018-04-12 13:11 UTC, edgarmueller commented on public/manifest.json
> +  "short_name": "React App",
Update short_name, name

2018-04-12 13:11 UTC, edgarmueller commented on tsconfig.test.json
> +}
newline

2018-04-12 13:11 UTC, edgarmueller commented on src/ui-metaschema.ts
> +export const uiMetaSchema = {
Add $schema keyword for version 7

2018-04-12 13:11 UTC, edgarmueller commented on src/ui-metaschema.ts
> +          'enum': ['Control']
`enum`s with just a single value should be replaced with `const`

2018-04-12 13:11 UTC, edgarmueller commented on src/ui-metaschema.ts
> +          'type': 'object',
`options` should itself be a definition and it should allow for objects where values can have an arbitrary type

2018-04-12 13:11 UTC, edgarmueller commented on src/ui-metaschema.ts
> +        'suggestion': {
Remove this, this would be an option

2018-04-12 13:11 UTC, edgarmueller commented on src/ui-metaschema.ts
> +    'label-object': {
Replace hyphen with camelCase

2018-04-12 13:11 UTC, edgarmueller commented on src/validation.ts
> +const extractErrors = (errors: ErrorObject[]): any[] =>
Remove references to `any` type, introduce respective interfaces if necessary,

2018-04-12 13:11 UTC, edgarmueller commented on test/validation.test.ts
> +} from './exampleUISchemas/validSchemas';
Use star import : `* as valid from ...`
References to actual schemas then can be prefixed with `valid` which is more explicit.

2018-04-12 13:11 UTC, edgarmueller commented on test/validation.test.ts
> +test('invalid control element, invalid label', () => {
Rename to 'layout label must be string'

2018-04-12 13:11 UTC, edgarmueller commented on test/validation.test.ts
> +/* tslint:disable:max-file-line-count */
Rename file to uischemaValidation or simliar

2018-04-12 13:11 UTC, edgarmueller commented on test/validation.test.ts
> +  expect(errors[0].message).toEqual('should be string');
I'd rather use `toHaveLength` or a similar matcher; It's not immediately obvious why the message is `should be string`.

2018-04-12 13:11 UTC, edgarmueller commented on test/validation.test.ts
> +test('invalid control element, label with additional properties', () => {
Rename to 'label object does not allow additional properties'

2018-04-12 13:11 UTC, edgarmueller commented on test/validation.test.ts
> +  expect(errors[0].message).toEqual('should have required property \'type\'');
Use template strings to avoid escaping

2018-04-12 13:11 UTC, edgarmueller commented on test/validation.test.ts
> +test('invalid control element, invalid suggestion type', () => {
Update this and move suggestion to `options` block

2018-04-12 13:21 UTC, edgarmueller commented
Also add a test case with a scope of nested properties

2018-04-12 14:08 UTC, AhmetTanakol commented on src/validation.ts
> +const extractErrors = (errors: ErrorObject[]): any[] =>
Do I need to create an interface for ui metaschema?

2018-04-12 15:40 UTC, AhmetTanakol commented
updated

2018-04-13 11:09 UTC, edgarmueller requested changes
Update schema to v7

2018-04-13 11:09 UTC, edgarmueller commented on src/models/jsonSchema.ts
> +export interface JsonSchema {
This interface mimics v4, but we are using v7

2018-04-13 16:10 UTC, AhmetTanakol commented
I tried to migrate json schema from v04 to v07. I think we should look at properties `$schema` and `default` in jsonforms. Is `$schema` should be string or JsonSchema? (maybe both?). I don't know why but we use single quotation marks for type definition of `default` property in Jsonforms.

![screen shot 2018-04-13 at 6 10 03 pm](https://user-images.githubusercontent.com/10375761/38745796-ed437aea-3f45-11e8-9d16-21137561291a.png)

2018-04-17 09:00 UTC, edgarmueller approved these changes

2018-04-17 09:02 UTC, edgarmueller commented
Yep, good points, we'll have a look, otherwise LGTM

2018-04-17 09:03 UTC, merged