add custom error messages for uischema validation
eclipsesource/jsonforms-ui-schema-editor pull request #8
Opened 2018-04-18 08:03 UTC by AhmetTanakol

Added ajv custom error messages

2018-04-25 12:20 UTC, edgarmueller requested changes
Can we add or modify a test that explicitly checks for the changed error messages?

2018-08-01 13:06 UTC, AhmetTanakol commented
Updated

2018-08-01 13:22 UTC, edgarmueller requested changes
Error messages regarding type seem to be wrong.

2018-08-01 13:22 UTC, edgarmueller commented on src/models/ui-metaschema.ts
> +          'label': 'Control label should be string,boolean or label object'
Add whitespace after comma

2018-08-01 13:22 UTC, edgarmueller commented on src/models/ui-metaschema.ts
> +          'type': 'Control should have an object property "type"'
Isn't type a string -> remove 'object'?

2018-08-01 13:22 UTC, edgarmueller commented on src/models/ui-metaschema.ts
> +                                'other than type,label,scope,options,suggestion and rule'
Add whitespace after each comma

2018-08-01 13:22 UTC, edgarmueller commented on src/models/ui-metaschema.ts
> +      'type': 'Root should have an object property "type"'
Should be of type string

2018-08-01 13:22 UTC, edgarmueller commented on src/models/ui-metaschema.ts
> +                            'other than type,elements,label and rule'
Whitespace after each comma

2018-08-03 09:43 UTC, edgarmueller approved these changes

2018-08-03 09:45 UTC, merged